tunnel: 0e7d6897-071b-47a2-9473-65713a338536
credentials-file: /home/nonroot/.cloudflared/0e7d6897-071b-47a2-9473-65713a338536.json

ingress:
  - hostname: "sir-labs.com"
    service: http://sir-nginx:80

  - hostname: "*.sir-labs.com"
    service: http://sir-nginx:80

  - service: http_status:404
